config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :users, only:[:index, :show, :edit, :update]
  get 'users/:id/post', to: 'users#user_post'
  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.order(id: "desc")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create(post_params)
    if post.save
      redirect_to controller: :posts, action: :index
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to controller: :posts, action: :index if @post.user_id != current_user.id
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params) if @post.user_id == current_user.id
    if @post.save
      redirect_to controller: :posts, action: :show
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy if post.user_id == current_user.id
    redirect_to controller: :posts, action: :index, alert: '削除？'
  end

  private
  def post_params
    params.require(:post).permit(:body).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
    redirect_to controller: :posts, action: :index if @user.id != current_user.id
  end

  def update
    user = User.find(params[:id])
    user.update(user_params) if user.id == current_user.id
    if user.save
      redirect_to controller: :posts, action: :index
    else
      render :edit
    end
  end



  def user_post
    @user = User.find(params[:id])
    @posts = Post.where(user_id: "#{params[:id]}").order(id: "desc")
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
</head>

<body>

  <div class="head">
    <nav>
      <div class="nav-wrapper grey darken-1">
        <%= link_to "Blog", root_path, class: "brand-logo" %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if user_signed_in? %>
          <li><%= link_to "投稿", new_post_path, data: {"turbolinks" => false} %></li>
          <li><%= link_to "マイページ", edit_user_path(current_user) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
          <% else %>
          <li><%= link_to "投稿", new_user_session_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>

  <%= yield %>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="js/materialize.min.js"></script>
</body>
</html>

app/views/posts/edit.html.erb
<div class="content_max_vh">
  <div class="row">
    <div class="col l2"></div>
    <div class="col l8">
      <%= form_for @post, method: :patch do |f| %>
      <%= f.text_area :body, :size => "20x7", class: "edit_text_area" %>
      <button class="btn waves-effect waves-light edit_button" type="submit" name="action">
      <%= f.submit "編集する" %>
      <i class="material-icons right">build</i>
      </button>
      <% end %>
    </div>
    <div class="col l2"></div>
  </div>
</div>



<!--   <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <textarea id="textarea1" class="materialize-textarea"></textarea>
          <label for="textarea1">Textarea</label>
        </div>
      </div>
    </form>
  </div> -->

app/views/posts/index.html.erb
<div class="content">

<% @posts.each do |post| %>
<div class="row">
  <div class="col s12 m2"></div>
  <div class="col s12 m8">
    <div class="card grey lighten-3">
      <div class="card-content">
        <p class="grey-text text-darken-3"><%= post.body %></p>
      </div>
      <div class="card-action">
        <%= link_to "", post_path(post.id), class: "grey-text text-darken-3 fas fa-info-circle fa-lg" %>
        <% if post.user == current_user %>
        <%= link_to "", edit_post_path(post.id), class: "grey-text text-darken-3 fas fa-wrench fa-lg" %>
        <%= link_to "", post_path(post.id), method: :delete, class: "grey-text text-darken-3 far fa-trash-alt fa-lg", data: { confirm: '削除しますか？' } %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="col s12 m2"></div>
<% end %>

</div>

app/views/posts/new.html.erb
<div class="content_max_vh">
  <div class="row">
    <div class="col l2"></div>
    <div class="col l8">
      <%= form_for @post, url: posts_path do |f| %>
      <%= f.text_area :body, placeholder: "text", autofocus: true, :size => "20x10", id: "textarea1", class: "grey lighten-5 new_text_field materialize-textarea" %>
      <button class="btn waves-effect waves-light post_button" type="submit" name="action">
        <%= f.submit "投稿する" %>
        <i class="material-icons right">send</i>
      </button>
      <% end %>
    </div>
    <div class="col l2"></div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="content_max_vh">

<div class="row">
  <div class="col s12 m2"></div>
  <div class="col s12 m8">
    <div class="card grey lighten-3">
      <div class="card-content">
        <p class="grey-text text-darken-3"><%= @post.body %></p>
      </div>
      <div class="card-action">
        <span class="grey-text text-darken-3"><%= @post.user.name %></span>&nbsp;&nbsp;&nbsp;&nbsp;
        <span class="grey-text text-darken-3"><%= @post.created_at.strftime('%Y年%m月%d日 %H:%M') %></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

        <% if @post.user == current_user %>
        <%= link_to "", edit_post_path(@post.id), class: "grey-text text-darken-3 fas fa-wrench fa-lg" %>
        <%= link_to "", post_path(@post.id), method: :delete, class: "grey-text text-darken-3 far fa-trash-alt fa-lg", data: { confirm: '削除しますか？' } %>
        <% end %>

      </div>
    </div>
  </div>
</div>
<div class="col s12 m2"></div>

</div>

app/views/users/edit.html.erb
<div class="content_max_vh">

  <div class="row">
    <div class="col l4"></div>
    <div class="col l4">
      <h4 class="user_edit_title"><i class="fas fa-user-edit"></i>&emsp;ユーザー情報編集</h4>
      <%= form_for @user, method: :patch do |f| %>
      <div class="row">
        <div class="input-field col l12">
          <div id="first_name" type="text" class="validate"><%= f.text_field :name %></div>
          <label class="active" for="first_name2">Name</label>
        </div>
      </div>


      <div class="row">
        <div class="input-field col s12">
          <div id="email" type="email" class="validate"><%= f.text_field :email %></div>
          <label class="active" for="first_name2">Email</label>
        </div>
      </div>
      <button class="btn waves-effect waves-light edit_button" type="submit" name="action">
      <%= f.submit "編集する" %>
      <i class="material-icons right">build</i>
      </button>
    </div>
    <div class="col l4"></div>
  </div>


  <% end %>
</div>

app/views/users/user_post.html.erb
<% if @user == current_user %>
<p>あなたの投稿一覧</p>
<% else %>
<p><%= @user.name %>さんの投稿一覧</p>
<% end %>

<% @posts.each do |post| %>
<div>
  DATE :<%= post.created_at %><br>
  BODY :<%= post.body %><br>
  <%= link_to "詳細", post_path(post.id) %>
  <% if @user == current_user %>
  <%= link_to "編集", edit_post_path(post.id) %>
  <%= link_to "削除", post_path(post.id), method: :delete %>
  <br><br>
  <% else %>
  <br><br>
  <% end %>
  <% end %>
</div>